// ============================================================================
// Exercise Library — 100+ exercises
// ============================================================================
const _EX_RAW = [
  ['Barbell Back Squat','Barbell','Legs, Core'],
  ['Squat','Barbell','Legs, Core'],
  ['Barbell Front Squat','Barbell','Legs, Core'],
  ['Front Squat','Barbell','Legs, Core'],
  ['Barbell Bench Press','Barbell','Chest, Arms, Shoulders'],
  ['Barbell Incline Bench Press','Barbell','Chest, Arms, Shoulders'],
  ['Incline Barbell Bench Press','Barbell','Chest, Arms, Shoulders'],
  ['Barbell Decline Bench Press','Barbell','Chest, Arms'],
  ['Barbell Row','Barbell','Back, Arms'],
  ['Bent Over Row','Barbell','Back, Arms'],
  ['Barbell Pendlay Row','Barbell','Back, Arms'],
  ['Overhead Press (Strict)','Barbell','Shoulders, Arms, Core'],
  ['Overhead Press','Barbell','Shoulders, Arms, Core'],
  ['Push Press','Barbell','Shoulders, Arms, Legs'],
  ['Barbell Deadlift (Conventional)','Barbell','Legs, Back, Arms'],
  ['Deadlift','Barbell','Legs, Back, Arms'],
  ['Barbell Sumo Deadlift','Barbell','Legs, Back'],
  ['Romanian Deadlift','Barbell','Legs, Core'],
  ['Barbell Hip Thrust','Barbell','Legs'],
  ['Barbell Good Morning','Barbell','Legs, Core'],
  ['Barbell Shrug','Barbell','Back'],
  ['Barbell Upright Row','Barbell','Back, Shoulders, Arms'],
  ['Barbell Curl','Barbell','Arms'],
  ['Barbell Skull Crusher','Barbell','Arms'],
  ['Barbell Lunges','Barbell','Legs'],
  ['Barbell Lunge','Barbell','Legs'],
  ['Barbell Step-up','Barbell','Legs'],
  ['Barbell Calf Raise','Barbell','Legs'],
  ['Barbell Floor Press','Barbell','Chest, Arms'],
  ['Barbell Pullover','Barbell','Chest, Back'],
  ['Barbell Split Squat','Barbell','Legs'],
  ['Barbell Landmine Press','Barbell','Shoulders, Arms, Core'],
  ['Barbell Landmine Row','Barbell','Back, Arms'],
  ['Barbell Glute Bridge','Barbell','Legs'],
  ['Barbell Reverse Lunge','Barbell','Legs'],
  ['Barbell Jefferson Curl','Barbell','Legs, Core'],
  ['Barbell Wrist Curl','Barbell','Arms'],
  ['Barbell Reverse Wrist Curl','Barbell','Arms'],
  ['Dumbbell Bench Press','Dumbbell','Chest, Arms'],
  ['Dumbbell Incline Press','Dumbbell','Chest, Arms, Shoulders'],
  ['Incline Dumbbell Bench Press','Dumbbell','Chest, Arms, Shoulders'],
  ['Dumbbell Shoulder Press','Dumbbell','Shoulders, Arms'],
  ['Dumbbell Arnold Press','Dumbbell','Shoulders, Arms'],
  ['Dumbbell Lateral Raise','Dumbbell','Shoulders'],
  ['Dumbbell Front Raise','Dumbbell','Shoulders'],
  ['Dumbbell Rear Delt Fly','Dumbbell','Shoulders, Back'],
  ['Dumbbell Row','Dumbbell','Back, Arms'],
  ['One Arm Dumbbell Row','Dumbbell','Back, Arms'],
  ['Dumbbell Pullover','Dumbbell','Chest, Back'],
  ['Dumbbell Curl','Dumbbell','Arms'],
  ['Seated Incline Dumbbell Curl','Dumbbell','Arms'],
  ['Dumbbell Hammer Curl','Dumbbell','Arms'],
  ['Dumbbell Concentration Curl','Dumbbell','Arms'],
  ['Dumbbell Triceps Extension','Dumbbell','Arms'],
  ['Dumbbell Kickback','Dumbbell','Arms'],
  ['Dumbbell Bulgarian Split Squat','Dumbbell','Legs'],
  ['Dumbbell Goblet Squat','Dumbbell','Legs, Core'],
  ['Dumbbell Lunges','Dumbbell','Legs'],
  ['Dumbbell Romanian Deadlift','Dumbbell','Legs'],
  ['Dumbbell Hip Thrust','Dumbbell','Legs'],
  ['Dumbbell Calf Raise','Dumbbell','Legs'],
  ['Dumbbell Shrug','Dumbbell','Back'],
  ['Dumbbell Russian Twist','Dumbbell','Core'],
  ['Dumbbell Floor Press','Dumbbell','Chest, Arms'],
  ['Dumbbell Farmer Walk','Dumbbell','Arms, Back, Core'],
  ['Dumbbell Step-up','Dumbbell','Legs'],
  ['Dumbbell Reverse Fly','Dumbbell','Shoulders, Back'],
  ['Dumbbell Overhead Triceps Extension','Dumbbell','Arms'],
  ['Dumbbell Decline Press','Dumbbell','Chest, Arms'],
  ['Dumbbell Chest Fly','Dumbbell','Chest'],
  ['Flat Bench Dumbbell Flye','Dumbbell','Chest'],
  ['Machine Chest Press','Machine','Chest, Arms'],
  ['Machine Shoulder Press','Machine','Shoulders, Arms'],
  ['Machine Lat Pulldown','Machine','Back, Arms'],
  ['Machine Seated Row','Machine','Back, Arms'],
  ['Machine Leg Press','Machine','Legs'],
  ['Leg Press','Machine','Legs'],
  ['Machine Leg Extension','Machine','Legs'],
  ['Leg Extension','Machine','Legs'],
  ['Machine Leg Curl','Machine','Legs'],
  ['Leg Curl','Machine','Legs'],
  ['Machine Chest Fly','Machine','Chest'],
  ['Machine Lateral Raise','Machine','Shoulders'],
  ['Machine Calf Raise','Machine','Legs'],
  ['Machine Biceps Curl','Machine','Arms'],
  ['Machine Triceps Extension','Machine','Arms'],
  ['Machine Hack Squat','Machine','Legs'],
  ['Machine Glute Kickback','Machine','Legs'],
  ['Cable Chest Fly','Cable','Chest'],
  ['Cable Lateral Raise','Cable','Shoulders'],
  ['Cable Face Pull','Cable','Shoulders, Back'],
  ['Cable Triceps Pushdown','Cable','Arms'],
  ['Cable Tricep Extension','Cable','Arms'],
  ['Cable Biceps Curl','Cable','Arms'],
  ['Cable Seated Row','Cable','Back, Arms'],
  ['Seated Cable Row','Cable','Back, Arms'],
  ['Cable Lat Pulldown','Cable','Back, Arms'],
  ['Lat Pull Down','Cable','Back, Arms'],
  ['Cable Pull-through','Cable','Legs, Core'],
  ['Cable Woodchop','Cable','Core'],
  ['Cable Overhead Triceps Extension','Cable','Arms'],
  ['Cable Hip Adduction','Cable','Legs'],
  ['Cable Hip Abduction','Cable','Legs'],
  ['Cable Crunch','Cable','Core'],
  ['Cable Rear Delt Fly','Cable','Shoulders, Back'],
  ['Pushup','Bodyweight','Chest, Arms'],
  ['Pull-up','Bodyweight','Back, Arms'],
  ['Chin-up','Bodyweight','Back, Arms'],
  ['Dip','Bodyweight','Chest, Arms'],
  ['Bodyweight Squat','Bodyweight','Legs'],
  ['Lunge','Bodyweight','Legs'],
  ['Plank','Bodyweight','Core'],
  ['Crunch','Bodyweight','Core'],
  ['Glute Bridge','Bodyweight','Legs'],
  ['Calf Raise','Bodyweight','Legs'],
  ['Burpee','Bodyweight','Core'],
  ['Mountain Climber','Bodyweight','Core'],
  ['Bicycle Crunch','Bodyweight','Core'],
  ['Wall Sit','Bodyweight','Legs'],
  ['Inverted Row','Bodyweight','Back, Arms'],
  ['Pike Pushup','Bodyweight','Shoulders, Arms'],
  ['Kettlebell Swing','Kettlebell','Legs, Core'],
  ['Kettlebell Goblet Squat','Kettlebell','Legs, Core'],
  ['Kettlebell Clean','Kettlebell','Legs, Back'],
  ['Kettlebell Snatch','Kettlebell','Shoulders, Legs, Core'],
  ['Kettlebell Turkish Get-up','Kettlebell','Core, Shoulders'],
  ['Kettlebell Windmill','Kettlebell','Core, Shoulders'],
  ['Kettlebell Row','Kettlebell','Back, Arms'],
  ['Kettlebell Press','Kettlebell','Shoulders, Arms'],
  ['Kettlebell Deadlift','Kettlebell','Legs, Core'],
  ['EZ Bar Curl','EZ Bar','Arms'],
  ['EZ Bar Skull Crusher','EZ Bar','Arms'],
  ['Skullcrusher','EZ Bar','Arms'],
  ['EZ Bar Pullover','EZ Bar','Chest, Back'],
  ['Band Pull-apart','Resistance Band','Shoulders, Back'],
  ['Band Lateral Walk','Resistance Band','Legs'],
  ['Band Face Pull','Resistance Band','Shoulders, Back'],
  ['Band Triceps Pushdown','Resistance Band','Arms'],
  ['Trap Bar Deadlift','Trap Bar','Legs, Back, Arms'],
  ['Trap Bar Shrug','Trap Bar','Back'],
  ['Trap Bar Farmer Walk','Trap Bar','Arms, Back, Core'],
  ['Sled Push','Sled','Legs'],
  ['Sled Pull','Sled','Legs, Back'],
  ['Sled Drag','Sled','Legs, Core'],
  ['Medicine Ball Slam','Medicine Ball','Core'],
  ['Medicine Ball Wall Ball','Medicine Ball','Legs, Core'],
  ['Medicine Ball Russian Twist','Medicine Ball','Core'],
  ['Medicine Ball Chest Pass','Medicine Ball','Chest, Arms'],
  ['Hanging Leg Raise','Bodyweight','Core'],
  ['Cable Hammer Curl','Cable','Arms'],
  ['Cable Pullover','Cable','Chest, Back'],
  ['Lying Leg Curl','Machine','Legs'],
  ['Hyperextension Bench','Bodyweight','Legs, Core'],
  ['Box Jump','Bodyweight','Legs'],
  ['Decline Push-up','Bodyweight','Chest, Arms'],
  ['Incline Push-up','Bodyweight','Chest, Arms'],
  ['Pec Deck Fly','Machine','Chest'],
  ['Cable Crossover','Cable','Chest'],
  ['Side Plank','Bodyweight','Core'],
  ['Calf Raise Machine (Standing)','Machine','Legs'],
  ['Calf Raise Machine (Seated)','Machine','Legs'],
  ['Seated Calf Raise','Machine','Legs'],
  ['Calf Press','Machine','Legs'],
];

const EX = _EX_RAW.map(e => ({
  id: e[0].replace(/[^a-zA-Z0-9]/g,'').toLowerCase(),
  name: e[0],
  category: e[1],
  muscles: e[2].split(', ')
}));

const byId = id => EX.find(e => e.id === id);
const byName = name => {
  if(!name)return null;
  // Exact match first
  const exact = EX.find(x => x.name === name);
  if(exact)return exact.id;
  // Case-insensitive match
  const lower = name.toLowerCase();
  const ci = EX.find(x => x.name.toLowerCase() === lower);
  if(ci)return ci.id;
  // Partial match (e.g. "Barbell Row" matches "Barbell Pendlay Row")
  const partial = EX.find(x => x.name.toLowerCase().includes(lower));
  return partial ? partial.id : null;
};
const getMuscleGroups = () => ['Chest','Back','Shoulders','Arms','Legs','Core'];
const getEquipmentTypes = () => ['Barbell','Dumbbell','Machine','Cable','Bodyweight','Kettlebell','EZ Bar','Resistance Band','Trap Bar','Sled','Medicine Ball'];
const getExercisesByMuscle = muscle => EX.filter(e => e.muscles.includes(muscle));
const getExercisesByEquipment = equip => EX.filter(e => e.category === equip);